ArkEcosystem/core-commander

menus/forger/help.sh
A small typo fix for the forger/help.sh
=> Forger Help.sh typo fix

actions/miscellaneous/updates.sh, commander.sh, helpers/reboot.sh, modules/environment.sh
Fixes #24 
Reduce the amount of reboots by checking for ` /var/run/reboot-required ` instead of blindly rebooting everytime.
=> Only reboot if necessary

menus/forger/args.sh
Pressing help didn't open Forger help menu and if you pressed 'X' to go back to the menu it opened help menu instead of main menu.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
=> fix: Returning back to Menu & Help

menus/relay/args.sh
Make correct call for opening Relay menu help.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
=> fix: Open Relay help menu

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
=> fix: wrong contributing link

README.md
Fixes the link to the contributing guidelines.
=> fix: new link to contributing guidelines

menus/main/menu.sh
Distributes the display of the various states equally on the whole line. Furthermore sets the color to white as intended.
=> refactor: distribute states accross whole line

menus/main/menu.sh
Distributes the display of the various versions equally on the whole line. Furthermore sets the color to white as intended.
=> refactor: distribute versions accross whole line

actions/log.sh, menus/main/args.sh
When chosing `Show Log` from the main menu, the commander will check if the log folder and file do exist before trying to tail the latter.
=> fix: check if logfile exists before tailing

menus/main/help.sh
Changes the output of the help text of the exit command so that it follows the established schema of `name (key)`.
=> chore: adjust help text

.gitignore, actions/core/update.sh, commander.sh, modules/modifications.sh
Implementation of https://github.com/ArkEcosystem/core-commander/issues/71#issuecomment-432614071.
Still has some nooks and crannies that need to be tested, also will change the file hash comparison tomorrow.
=> feat: update plugins.js and network.json on updates

CHANGELOG.md, actions/apps/forger.sh, ecosystem.config.js
The forger parameters `bip38` and `password` are now passed as environment variables.
Before:
After:
Depends on https://github.com/ArkEcosystem/core/pull/1224
=> fix: dont expose bip38 password in process monitor

README.md, actions/apps/explorer.sh, actions/core/configure.sh, actions/core/install.sh, actions/core/uninstall.sh, actions/core/update.sh, actions/miscellaneous/alias.sh, helpers/core.sh, menus/commander/help.sh, menus/core/help.sh, menus/core/menu.sh, menus/explorer/help.sh, menus/explorer/menu.sh, menus/forger/help.sh, menus/main/help.sh, menus/main/menu.sh, menus/relay/help.sh, modules/update.sh, scripts/ntp.sh
Double checked everything, won't break any script.
=> ARK to Ark in all cases but env variables

scripts/nodejs.sh
Goes hand in hand with https://github.com/ArkEcosystem/core/pull/1237
=> chore: install node 10

modules/database.sh
Ask for an action if the database user or database already exists.
Resolves https://github.com/ArkEcosystem/core-commander/issues/41
=> refactor: ask for action if database or database user exists

modules/environment.sh
This will make sure the database variables always exist on every start.
Resolves https://github.com/ArkEcosystem/core-commander/issues/54
=> fix: make sure database defaults always exist

actions/core/configure/log-level.sh
It was easy for me to pick an option as the log level when trying to see error messages more clearly, though it might not be intuitive that the three main options used by Core are winston's `debug, info and warn(ing)`.
=> feat: useful options for log level

actions/apps/explorer.sh, actions/core/update.sh, modules/update.sh
This PR rephrases the "latest version that we support" messages so they stay inside of the bounds.
=> chore: rephrase latest version messages to stay inside of bounds

menus/explorer/menu.sh
The uninstall and update option was shown only when the explorer was `On`, fixes #85.
=> fix: move explorer uninstall and update to correct condition

menus/core/help.sh, menus/explorer/help.sh
Updates the explorer help page.
=> chore: update explorer help

ecosystem.config.js
Resolves https://github.com/ArkEcosystem/core/issues/1421
=> chore: increase kill_timeout to 30 seconds

actions/core/configure.sh, menus/core/args.sh, menus/core/menu.sh
Add an option to quickly reset the configuration of core.
=> feat: reset configuration

actions/apps/forger.sh, actions/core/configure.sh, actions/core/update.sh, menus/commander/help.sh, modules/environment.sh
Remove the mainnet checks we had in place until release.
=> chore: remove mainnet checks
