ArkEcosystem/core-commander

modules/environment.sh, scripts/ntp.sh, scripts/postgresql.sh, scripts/redis.sh
Fixes #25
`pgrep -x` does not require root privileges. Exiting a log view after sudo timeout should not cause a password prompt again.
Also removed one superfluous sudo call in `modules/environment.sh` which causes a prompt before the message that sudo is being called is shown.
=> Drop some sudo calls

actions/core/update.sh
Fixes #29 
Remember the status of the forger/relay prior updating and restart them if necessary once finished.
Test plan:
Started the relay, performed a core update and the relay was restarted.
Didn't test the forger, but should behave the same in theory.
=> core: Restart services after update

actions/miscellaneous/updates.sh, modules/environment.sh
Allows the Commander to launch without a `sudo` prompt.
`sudo updatedb` is not needed according to #33 and `sudo apt-get update` is not necessary since `/usr/lib/update-notifier/apt-check` is the preferred way of checking for updates.
=> Allow commander to launch without sudo

actions/apps/explorer.sh, actions/apps/forger.sh, actions/apps/relay.sh, commander.sh, helpers/pm2status.sh
Partial fix for #21.
The errors
`==> Deleting Forger... [PM2][ERROR] Process ark-core-forger not found`
and
` ==> Deleting Relay... [PM2][ERROR] Process ark-core-relay not found`
are prevented by checking the status of the process before calling delete.
The added `pm2status` helper also fixes a potential issue, where the name of a process overlaps with the name of another process.
Scenario: status of `ark-core` is wanted, only `ark-core-relay` is active.
The previous grep call would have erroneously returned the status of ark-core-relay.
Will take a look at the remaining errors in the issue later.
=> Add pm2status helper, check status before trying to delete relay/forger

actions/core/update.sh
This is a follow-up to #29.
Missed this one earlier since I didn't test the restart when doing an update right after starting the commander before the menu is shown.
`STATUS_RELAY` and `STATUS_FORGER` are not set until menu_main is first called.
While at it only stop the service if it is running.
=> Query service status before core update

actions/core/uninstall.sh
Fixes #21 
The `Error: ENOENT: no such file or directory, uv_cwd` was caused by calling `rm -rf` on the current working directory which at this stage points to `$CORE_DIR`.
Fixed by moving out of the directory before calling `rm -rf`.
=> Fix error during uninstall

menus/core/args.sh
After core uninstall I'm still in the core menu and I can again select Update/Uninstall even though the core is not installed.
I believe you should go to the main menu after core uninstall.
=> Core uninstall

actions/core/update.sh
`lerna bootstrap` was never executed, because of a typo.
=> Fix lerna bootstrap after update

actions/core/configure.sh
Resolves #47 
Simplest grep check if config variable is already present in
`~/.ark/.env`
If config variable is present, do nothing.
If config variable is not present, append it.
Possible improvement using sed for ARK_P2P_PORT which is dependent on network.
Fix is for following scenario in core-commander:
A. Manage ARK Core
C. Configure ARK Core
We found an ARK Core configuration, do you want to overwrite it? [y/N] : y
=> fix: avoid duplicate config values for ark core configuration

actions/apps/explorer.sh
The explorer installation does always show a positive message, even when the installation/building of the explorer fails - see #49. This PR adds checks against the return code of the `yarn` commands and presents the user with a corresponding message.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
=> Adds error handling to explorer installation

actions/apps/explorer.sh, actions/apps/forger.sh, actions/apps/relay.sh, helpers/pm2status.sh
This changes the pm2status function to use `pm2 describe` rather than `pm2 status`, as newer versions of pm2 add an extra `version` column in `pm2 status` which breaks the ability to check if the relay/forger/explorer are online or not. Scripts that rely on pm2status have also been updated to work with the output of `pm2 describe` by changing `$10` to `$13`.
The alternative approach would be to continue using `pm2 status` but modifying relay.sh, forger.sh and relay.sh to use the 6th column rather than the 5th, i.e. `$12` instead of `$10` to accommodate the new column, but this would break for users still using the old version of pm2. This approach maintains compatibility across both versions.
=> Use pm2 describe rather than pm2 status to check status of relay/forger/explorer

actions/apps/explorer.sh, actions/apps/forger.sh, actions/apps/relay.sh, commander.sh, ecosystem.config.js, modules/dependencies.sh
Move the configs for relay, forger and explorer to a central ecosystem.config.js  (reference: https://pm2.io/doc/en/runtime/guide/ecosystem-file/ )
Now one can simply fire up a relay by executing `pm2 start ecosystem.config.js  --only ark-core-relay`  instead of having to replicate what commander did previously:
`    pm2 start "$CORE_DIR/packages/core/bin/ark" --name ark-core-relay -- relay --data "$CORE_DATA" --config "$CORE_CONFIG" --token "$CORE_TOKEN" --network "$CORE_NETWORK" `
The `ecosystem.config.js` leverages more options, essentially we can now prevent an endless restart loop as described here https://github.com/ArkEcosystem/core/issues/849 After 5 restarts in less than 5 minutes pm2 will stop trying. 
I added a new npm dependency `dotenv` which is used to read the `.commander` …
=> Use ecosystem.config.js

menus/core/args.sh
In the parsing of the ARK Core menu options the `c|C` case was present twice.
=> removes double case in menu option parsing

modules/dependencies.sh
Adds the `apt-transport-https` package so that we can fetch packages over https. 
```bash
Reading package lists...
E: The method driver /usr/lib/apt/methods/https could not be found.
E: Failed to fetch https://deb.nodesource.com/node_9.x/dists/xenial/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
=> fix: add 'apt-transport-https' to base dependencies

modules/dependencies.sh
Adds the package `update-notifier` to the base dependencies.
```
==> There are /home/devnet/core-commander/actions/miscellaneous/updates.sh: line 9: /usr/lib/update-notifier/apt-check: No such file or directory system updates available. /home/devnet/core-commander/actions/miscellaneous/updates.sh: line 10: /usr/lib/update-notifier/apt-check: No such file or directory of them are security updates!
```
=> fix: add 'update-notifier' to base dependencies

modules/database.sh, modules/environment.sh
Inserts the system user into .env instead of "ark". Removes duplicate user creation and permission setup.
=> refactor: only create a psql account for the system user

actions/core/install.sh, actions/core/uninstall.sh, actions/core/update.sh, actions/miscellaneous/updates.sh, commander.sh, menus/core/menu.sh, modules/state.sh, modules/versions.sh
Moves `get_versions` out of `refresh_states` and calls it only when necessary, i.e. on startup and after system or core updates, allowing the main menu to load faster, see #83
=> refactor: get state/versions only when necessary

actions/core/configure.sh, actions/core/configure/hosts-and-ports.sh
@adrian69 noticed that the JSON-RPC variables were missing an underscore.
=> fix: correct JSON-RPC variable names

actions/apps/explorer.sh
Fixes #106 by changing to the `commander_dir` directory before deleting the explorer directory.
=> fix: cd to commander_dir before explorer uninstall

modules/database.sh
Fixes #108 by using the env variables `ARK_DB_USERNAME` and `ARK_DB_USERNAME` instead of `USER` and the hardcoded password. Also removes a typo (usename -> username).
=> fix: use env variables for database creation
